# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  sliding_base_joint:
    has_velocity_limits: true
    max_velocity: 0.15 # 0.25 meter per sec for prismatic joint
    has_acceleration_limits: true
    max_acceleration: 0.5 # m/s^2 for prismatic joint
    min_position: -0.675
    max_position: 0.675
    # min_position: 0.0
    # max_position: 0.0
joint_limits:
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.25
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.25
    max_position: 0.0135 #I added, use 0.05 on bumblebee
    min_position: -2.62 #I added
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.25
    max_position: 2.01 
    min_position: -2.43
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.25
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.25
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1.1
    has_acceleration_limits: true
    max_acceleration: 0.25
